// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfDNZxFwCAkkVnHaZ4pLcM7H4UBfdMy1I',
    appId: '1:138237315826:web:4afa09cb823bfc36125e6b',
    messagingSenderId: '138237315826',
    projectId: 'flutterchatapp-e82b8',
    authDomain: 'flutterchatapp-e82b8.firebaseapp.com',
    storageBucket: 'flutterchatapp-e82b8.appspot.com',
    measurementId: 'G-G1WFYD4DNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJF68in23XL9Rzzjc5q3LgqnlEDVRkQNQ',
    appId: '1:138237315826:android:dbccbc79aaf6a246125e6b',
    messagingSenderId: '138237315826',
    projectId: 'flutterchatapp-e82b8',
    storageBucket: 'flutterchatapp-e82b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_i9eP7IWJ3f7HF3B-okTJH2OqTa9TfXY',
    appId: '1:138237315826:ios:30269e52b88e2b70125e6b',
    messagingSenderId: '138237315826',
    projectId: 'flutterchatapp-e82b8',
    storageBucket: 'flutterchatapp-e82b8.appspot.com',
    androidClientId: '138237315826-s4as1aca5orsts3og7p063kccnkr2feg.apps.googleusercontent.com',
    iosClientId: '138237315826-h5uq66ojt7qllkovgoib4c2da8228bv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_i9eP7IWJ3f7HF3B-okTJH2OqTa9TfXY',
    appId: '1:138237315826:ios:30269e52b88e2b70125e6b',
    messagingSenderId: '138237315826',
    projectId: 'flutterchatapp-e82b8',
    storageBucket: 'flutterchatapp-e82b8.appspot.com',
    androidClientId: '138237315826-s4as1aca5orsts3og7p063kccnkr2feg.apps.googleusercontent.com',
    iosClientId: '138237315826-h5uq66ojt7qllkovgoib4c2da8228bv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
